### ISSUE TITLE
sbt run throw an exception 

### ISSUE THREAD

**Issue by 123avi** [liosedhel/akkapaint#1]
cloned the project and executing sbt run :

```
java.lang.RuntimeException: error occured while compiling protobuf files: Cannot run program "protoc": error=2, No such file or directory
at sbtprotobuf.ProtobufPlugin$.executeProtoc(ProtobufPlugin.scala:68)
	at sbtprotobuf.ProtobufPlugin$.sbtprotobuf$ProtobufPlugin$$compile(ProtobufPlugin.scala:81)
	at sbtprotobuf.ProtobufPlugin$$anonfun$sourceGeneratorTask$1$$anonfun$5.apply(ProtobufPlugin.scala:107)
	at sbtprotobuf.ProtobufPlugin$$anonfun$sourceGeneratorTask$1$$anonfun$5.apply(ProtobufPlugin.scala:106)
	at sbt.FileFunction$$anonfun$cached$1.apply(Tracked.scala:235)
	at sbt.FileFunction$$anonfun$cached$1.apply(Tracked.scala:235)
	at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3$$anonfun$apply$4.apply(Tracked.scala:249)
	at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3$$anonfun$apply$4.apply(Tracked.scala:245)
	at sbt.Difference.apply(Tracked.scala:224)
	at sbt.Difference.apply(Tracked.scala:206)
(...)
```

**Comment by liosedhel** [comment]
Thanks for reporting. Could you verify @123avi ? Now I am abroad so it is only a quick optimistic bugfix.

**Comment by 123avi** [comment]
thanks
